services:
    bot:
                container_name: e-office-api-v2-bot
                restart: unless-stopped
                build:
                    context: .
                    dockerfile: Dockerfile
                environment:
                    - NODE_ENV=production
    postgres:
                container_name: e-office-api-v2-postgres
                image: postgres:latest
                restart: unless-stopped
                environment:
                    - POSTGRES_USER=e-office-api-v2
                    - POSTGRES_PASSWORD=90d467e0d673bc1a8fba21ed
                    - POSTGRES_DB=e-office-api-v2
                volumes:
                    - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
    
networks:
    default: {}